spring:
  application:
    name: search-service
  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    representation:
      uuid: standard
    uri: ${SEARCH_MONGODB_URI:mongodb://localhost:27017/search-service}

server:
  port: ${SERVER_PORT:8085}

app:
  internal:
    api-key: ${APP_INTERNAL_API_KEY:vetau-internal-key}

search:
  mongodb:
    ticket-collection: ${SEARCH_TICKET_COLLECTION:ticket-search}
